# Site settings
title: GFW Style Guidelines
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Global Forest Watch Style Guidelines
baseurl: "/gfw-style-guides" # the subpath of your site, e.g. /blog/
url: "http://vizzuality.github.io/" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
permalink: none
paginate: 1
# Build settings
markdown: kramdown
